# Generated by Django 4.1.3 on 2023-02-06 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ophthclinic', '0002_client_dosageforms_medications'),
    ]

    operations = [
        migrations.CreateModel(
            name='thewholemed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('to', models.DateField()),
                ('perday', models.IntegerField()),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ophthclinic.medications')),
            ],
        ),
        migrations.CreateModel(
            name='prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientid', models.IntegerField()),
                ('patientmed', models.ManyToManyField(to='ophthclinic.thewholemed')),
            ],
        ),
    ]
