# Generated by Django 4.1.3 on 2023-02-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ophthclinic', '0005_alter_client_asthma_alter_client_atopy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='asthma',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='atopy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='bov',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='burning',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='cataract',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='cvs',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='diabetesmellitus',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='client',
            name='diplopia',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='epiphoria',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='foreign',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='glare',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='glucoma',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='glucomasurgery',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='headache',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='client',
            name='hypertension',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='ihd',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='kidney',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='liver',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='refractive',
            field=models.BooleanField(default=False),
        ),
    ]
