# Generated by Django 4.1.3 on 2023-02-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ophthclinic', '0006_alter_client_asthma_alter_client_atopy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='deabetesnumber',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='leftleft',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='leftmiddle',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='leftright',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='rightleft',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='rightmiddle',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='rightright',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
