# Generated by Django 4.1.3 on 2023-02-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ophthclinic', '0007_alter_client_deabetesnumber_alter_client_leftleft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='leftleftr',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='leftmiddler',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='leftrightr',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='rightleftr',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='rightmiddler',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='rightrightr',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
